//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.01 at 02:16:01 PM EDT 
//


package testingFiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bug complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bug">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reporter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="votes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="confirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="note_list" type="{}NoteList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Generated by JAXB
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bug", propOrder = {
    "id",
    "state",
    "summary",
    "reporter",
    "owner",
    "votes",
    "confirmed",
    "resolution",
    "noteList"
})
public class Bug {

	/** ID of the bug */
	public int id;
    /** Current state of the bug */
    @XmlElement(required = true)
    public String state;
    /** Bug summary entered by the user when first reporting a bug */
    @XmlElement(required = true)
    public String summary;
    /** User id of person that reported the bug */
    @XmlElement(required = true)
    public String reporter;
    /** User id of person responsible for fixing the bug */
    @XmlElement(required = true)
    public String owner;
    /** Number of votes of users requesting the bug be fixed */
    public int votes;
    /** True if the bug is confirmed through replication of the incorrect actual results */
    public boolean confirmed;
    /** A description of why the bug is closed, if closed */
    @XmlElement(required = true)
    public String resolution;
    /** A list of notes that may optionally be added to a bug as it moves through its states */
    @XmlElement(name = "note_list", required = true)
    public NoteList noteList;

    /**
     * Gets the value of the id property.
     * @return id of the bug
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * @param value sets the id to the given value
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the state property.
     * @return the state of the {@link Bug} as a {@link String}
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value the state of the {@link Bug}
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return the summary of the {@link Bug} as a {@link String}
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value the summary for the {@link Bug}
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the reporter property.
     * 
     * @return the user id of the reporter
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * Sets the value of the reporter property.
     * 
     * @param value the user id of the reporter
     */
    public void setReporter(String value) {
        this.reporter = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return the user id of the owner
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value the user id of the owner
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the votes property.
     * 
     * @return the number of votes for fixing the bug
     */
    public int getVotes() {
        return votes;
    }

    /**
     * Sets the value of the votes property.
     * 
     * @param value the number of votes for fixing the bug
     */
    public void setVotes(int value) {
        this.votes = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     * @return true if the bug has been replicated
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     * @param value true if the bug has been replicated
     */
    public void setConfirmed(boolean value) {
        this.confirmed = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * @return the value of the {@link Bug}'s resolution if the {@link Bug} is closed
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value the resolution of the {@link Bug} if closed
     */
    public void setResolution(String value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the noteList property.
     * 
     * @return a list of notes associated with the {@link Bug}
     */
    public NoteList getNoteList() {
        return noteList;
    }

    /**
     * Sets the value of the noteList property.
     * 
     * @param value list of notes associated with the {@link Bug}
     */
    public void setNoteList(NoteList value) {
        this.noteList = value;
    }

}
