//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.01 at 02:16:01 PM EDT 
//


package testingFiles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import testingFiles.Bug;


/**
 * <p>Java class for BugList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BugList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Bug" type="{}Bug" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Generated by JAXB
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BugList", propOrder = {
    "bug"
})
public class BugList {

	/** List of bugs */
    @XmlElement(name = "Bug", required = true)
    public List<Bug> bug;

    /**
     * Gets the value of the bug property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bug property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBug().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bug }
     * 
     * @return a list of {@link Bug}s
     */
    public List<Bug> getBug() {
        if (bug == null) {
            bug = new ArrayList<Bug>();
        }
        return this.bug;
    }

}
