//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.01 at 02:16:01 PM EDT 
//


package testingFiles;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.ncsu.csc216.bug_tracker.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 * @author Generated by JAXB
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName BUGS_QNAME = new QName("", "Bugs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.ncsu.csc216.bug_tracker.xml
     */
    public ObjectFactory() {
    	//Generated constructor
    }

    /**
     * Create an instance of {@link BugList }
     * @return a list of {@link Bug}s in a new instance of a {@link BugList}
     */
    public BugList createBugList() {
        return new BugList();
    }

    /**
     * Create an instance of {@link NoteList }
     * @return a list of notes in a new instance of a {@link NoteList}
     */
    public NoteList createNoteList() {
        return new NoteList();
    }

    /**
     * Create an instance of {@link Bug }
     * @return an instance of a new {@link Bug} object
     */
    public Bug createBug() {
        return new Bug();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BugList }{@code >}}
     * @param value list of bugs to create
     * @return a list of bugs ready to encode in XML
     */
    @XmlElementDecl(namespace = "", name = "Bugs")
    public JAXBElement<BugList> createBugs(BugList value) {
        return new JAXBElement<BugList>(BUGS_QNAME, BugList.class, null, value);
    }

}
